using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Text;
namespace ThisClass
{
    public partial class ThisClassGenerator
    {
        internal static readonly SyntaxTriviaList LeadingCompilationTrivia = SyntaxFactory.ParseLeadingTrivia("""
        // <auto-generated/>
        #nullable enable
        """);

        internal static readonly ClassDeclarationSyntax ThisClassPartialClass = SyntaxFactory.ClassDeclaration("ThisClass")
            .WithModifiers(SyntaxFactory.TokenList(
                SyntaxFactory.Token(SyntaxKind.PublicKeyword),
                SyntaxFactory.Token(SyntaxKind.StaticKeyword),
                SyntaxFactory.Token(SyntaxKind.PartialKeyword)
            ));

        internal static readonly SyntaxTriviaList FullNameFieldTrivia = SyntaxFactory.ParseLeadingTrivia("""
        /// <summary>
        /// Gets the fully qualified name of the parent class, including the namespace but not the assembly.
        /// </summary>
        
        """);
    }
}
