using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
namespace ThisClass
{
    public partial class ThisClassGenerator
    {
        internal static readonly SyntaxTriviaList LeadingCompilationTrivia = SyntaxFactory.ParseLeadingTrivia("""
        // <auto-generated/>
        #pragma warning disable CS0108,CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
        #nullable enable
        """);

        internal static readonly ClassDeclarationSyntax ThisClassPartialClass = SyntaxFactory.ClassDeclaration("ThisClass")
            .WithModifiers(SyntaxFactory.TokenList(
                SyntaxFactory.Token(SyntaxKind.PublicKeyword),
                SyntaxFactory.Token(SyntaxKind.StaticKeyword),
                SyntaxFactory.Token(SyntaxKind.PartialKeyword)
            ));

        internal static readonly SyntaxTriviaList FullNameFieldTrivia = SyntaxFactory.ParseLeadingTrivia("""
        /// <summary>
        /// Gets the fully qualified name of the parent class, including the namespace but not the assembly.
        /// </summary>
        
        """);
    }
}
